# Generated by Django 5.1.7 on 2025-06-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tipoplano',
            options={'ordering': ['nome']},
        ),
    ]
