# Generated by Django 5.1.7 on 2025-03-31 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tipoplano_remove_cliente_plano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_ultima_dieta',
            field=models.DateField(blank=True, help_text='Data em que a última dieta foi atribuída', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ultimo_treino',
            field=models.DateField(blank=True, help_text='Data em que o último treino foi atribuído', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='trocas_exercicios_restantes',
            field=models.IntegerField(default=0, help_text='Número de trocas de exercícios restantes no período atual'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='trocas_refeicoes_restantes',
            field=models.IntegerField(default=0, help_text='Número de trocas de refeições restantes no período atual'),
        ),
        migrations.AddField(
            model_name='tipoplano',
            name='intervalo_atualizacao_treino_dieta',
            field=models.IntegerField(default=60, help_text='Intervalo em dias para atualização de treino e dieta'),
        ),
        migrations.AddField(
            model_name='tipoplano',
            name='limite_trocas_exercicios',
            field=models.IntegerField(default=1, help_text='Número de trocas de exercícios permitidas'),
        ),
        migrations.AddField(
            model_name='tipoplano',
            name='limite_trocas_refeicoes',
            field=models.IntegerField(default=1, help_text='Número de trocas de refeições permitidas'),
        ),
        migrations.AddField(
            model_name='tipoplano',
            name='periodo_trocas_dias',
            field=models.IntegerField(default=7, help_text='Período em dias para realizar trocas após receber treino/dieta'),
        ),
        migrations.AddField(
            model_name='tipoplano',
            name='trocas_ilimitadas',
            field=models.BooleanField(default=False, help_text='Se True, permite trocas ilimitadas de exercícios e refeições'),
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='core.treino')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('calorias', models.IntegerField()),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='core.dieta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrocaExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_troca', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_exercicios', to='core.cliente')),
                ('exercicio_antigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_antigo', to='core.exercicio')),
                ('exercicio_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_novo', to='core.exercicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrocaRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_troca', models.DateField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_refeicoes', to='core.cliente')),
                ('refeicao_antiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_antiga', to='core.refeicao')),
                ('refeicao_nova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_nova', to='core.refeicao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
