# Generated by Django 5.1.7 on 2025-05-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
