# Generated by Django 5.1.7 on 2025-05-23 20:24

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trocaexercicio',
            options={'ordering': ['-data_solicitacao']},
        ),
        migrations.AlterModelOptions(
            name='trocarefeicao',
            options={'ordering': ['-data_solicitacao']},
        ),
        migrations.RemoveField(
            model_name='trocaexercicio',
            name='data_troca',
        ),
        migrations.RemoveField(
            model_name='trocarefeicao',
            name='data_troca',
        ),
        migrations.AddField(
            model_name='trocaexercicio',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercicios_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trocaexercicio',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trocaexercicio',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 23, 20, 24, 10, 150717, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trocaexercicio',
            name='exercicio_sugerido',
            field=models.CharField(blank=True, help_text='Sugestão de exercício quando não há um específico', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trocaexercicio',
            name='observacoes_resposta',
            field=models.TextField(blank=True, help_text='Observações do profissional', null=True),
        ),
        migrations.AddField(
            model_name='trocaexercicio',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10),
        ),
        migrations.AddField(
            model_name='trocarefeicao',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refeicoes_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trocarefeicao',
            name='data_resposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trocarefeicao',
            name='data_solicitacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trocarefeicao',
            name='observacoes_resposta',
            field=models.TextField(blank=True, help_text='Observações do profissional', null=True),
        ),
        migrations.AddField(
            model_name='trocarefeicao',
            name='refeicao_sugerida',
            field=models.CharField(blank=True, help_text='Sugestão de refeição quando não há uma específica', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trocarefeicao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='trocaexercicio',
            name='exercicio_novo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_novo', to='core.exercicio'),
        ),
        migrations.AlterField(
            model_name='trocaexercicio',
            name='motivo',
            field=models.TextField(help_text='Motivo da solicitação de troca'),
        ),
        migrations.AlterField(
            model_name='trocarefeicao',
            name='motivo',
            field=models.TextField(help_text='Motivo da solicitação de troca'),
        ),
        migrations.AlterField(
            model_name='trocarefeicao',
            name='refeicao_nova',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trocas_como_nova', to='core.refeicao'),
        ),
    ]
