# Generated by Django 5.1.7 on 2025-05-23 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_trocaexercicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='dieta',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='historicodieta',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.AlterModelOptions(
            name='historicotreino',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.AlterModelOptions(
            name='treino',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('crn', models.CharField(blank=True, help_text='Conselho Regional de Nutricionistas', max_length=20, null=True)),
                ('perfil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutricionista', to='core.perfil')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='core.perfil')),
            ],
            options={
                'verbose_name_plural': 'Personais',
                'ordering': ['nome'],
            },
        ),
    ]
